# Generated by Django 5.1 on 2024-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='The name of the author goes here')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time at which the post was created')),
                ('content', models.TextField(verbose_name='This is where you enter the text of the post')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Optional image')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Optional video')),
            ],
        ),
    ]
